#279 - 메타데이터 수정 후 저장 시 발생하는 에러
BEOKS/DicomProject pull request #280
Opened 2022-05-22 15:27 UTC by doheez

2022-05-28 12:37 UTC, BEOKS requested changes

2022-05-28 12:37 UTC, BEOKS commented on client/src/component/Drawer/CreateProjectDialog.tsx
>          if (project.projectName === "현재 선택된 프로젝트가 없습니다.") {
다른 코드에서도 프로젝트가 선택되었는지 아닌지 판별이 필요한 경우가 생길 수도 있으니까 이런 리터럴 상수 부분은 따로 ENV  파일에 명시하거나 
```typescript
const NO_PROJECT_NAME_STATEMENT="현재 선택된 프로젝트가 없습니다."
```
라고 ProjectDrawerReducer내부에 const 상수에 선언해서 관리하는게 좋을 듯, 이 부분에서는 drawer에 선언된 부분을 import해서 사용하면 되니까

2022-05-28 12:37 UTC, BEOKS commented on client/src/component/Drawer/CreateProjectDialog.tsx
>          if (project.projectName === "현재 선택된 프로젝트가 없습니다.") {
조오금 억지긴 한데 만약 사용자가 "현재 선택된 프로젝트가 없습니다."라는 프로젝트를 만들면 리액트가 프로젝트가 선택 안된 걸로 인식할 수 있어서 ```NO_PROJECT_NAME_STATEMENT``` 값은 undefined로 정의하는게 좋을 듯?

2022-05-28 13:04 UTC, BEOKS requested changes

2022-05-28 13:04 UTC, BEOKS commented on client/src/Page.js
> +                            : <div></div>
이 부분이 여러 조건 때문에 복잡한데 내가 리팩토링할게

2022-05-28 13:17 UTC, BEOKS requested changes

2022-05-28 13:17 UTC, BEOKS commented on client/src/api/metadata.ts
> +const updateMetaData = (body: Body, metadataId: string) => {
메타데이터를 가져오는 API를 사용했을 때, dispatch 말고 다른 작업도 선언할 수 있으니까, dispatch를 인자로 넣기 보다는 아래처럼 성공했을 때, 데이터를 받아서 어떻게 처리할지를 정의하는 함수를 인자로 넣어주고
```typescript
const getMetaData = (project: Project, onSuccess: (metaData)=>void){
...
axios.get(url)
        .then(response => {
            onSuccess(response.data.body) 
        })
...
}
```
이걸 호출하는 부분에서 아래처럼 바꾸면 좋을듯
```javascript
//Page.js 40:1
getMetaData(project, (metaData)=>dispatch(MetaDataGridAction.setMetaData(metaData)));
```

2022-05-28 14:33 UTC, doheez commented on client/src/component/Drawer/CreateProjectDialog.tsx
>          if (project.projectName === "현재 선택된 프로젝트가 없습니다.") {
"현재 선택된 프로젝트가 없습니다."는 아무 프로젝트도 선택되지 않았을 때 최상단 메뉴바에 저 문구를 보이게 해서 사용자한테 알리려는 의도였긴 한데 "현재 선택된 프로젝트가 없습니다."라는 프로젝트 자체를 만들어버리면 곤란하긴 하겠다. 그건 생각 못했네!

2022-05-28 15:03 UTC, doheez commented on client/src/Page.js
> +    const openDrawer = useSelector(state => state.ProjectDrawerReducer.openDrawer);
변수명이 너무 길어지는 것 같아서 최대한 줄여서 쓰려고 하는 경향이 있었는데 줄여 쓰면 앞으로 추가할 기능에 혼선이 생길 수도 있다는 것도 생각해야 되겠구나. 고마워~~

2022-05-28 15:06 UTC, doheez commented on client/src/api/metadata.ts
> +const updateMetaData = (body: Body, metadataId: string) => {
오 좋은 생각이다 수정할게

2022-05-28 16:15 UTC, doheez commented
렌더링이 왜인지 리팩토링 전보다 더 많이 발생하는 것 같은데 왜 그럴까.......😭

2022-05-29 04:50 UTC, BEOKS commented on client/src/Page.js
> +    }
내가 리팩토링하는데 페이지 내부에 훅을 정의해둬서 그래... 지금은 수정했어~

2022-05-29 04:52 UTC, BEOKS approved these changes

2022-05-29 08:23 UTC, merged